version: '3.8'

services:
  mysql:
    build: .
    ports:
      - "63306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: carsdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
